### ISSUE TITLE
wont find the correct azcopy in path

### ISSUE THREAD

**Issue by SeidChr** [kheiakiyama/install-azcopy-action#3]
hi

using this action on linux will add path to the "path" env, which contains another folder, and not the assembly itself. thus commandline will only find the dotnet azcopy and not the one you have installed.

i have to use a commandline like this to make it work: 
`      run: /opt/hostedtoolcache/azcopy/v10/x64/azcopy_linux_amd64_10.3.4/azcopy ...`

also would be nice to declare an alias, so one can be sure to not use the false azcopy (version 7.3 ist installed along with dotnet core)

**Comment by kheiakiyama** [comment]
@SeidChr Thank you for your feedback.

I agree with your idea.
So I will implement using it.

Thanks.

**Comment by kheiakiyama** [comment]
@SeidChr I fixed this bug and release again.
Please use it.

And thank you for your usefull feedback.

**Comment by SeidChr** [comment]
Thank you!

I realized that you broke my build :)
Would be cool if you use tags and add one, every time you do a "release".
So that the old version is still available and other peoples builds wont just fail out of a sudden.

Otherwise its working great!

**Comment by kheiakiyama** [comment]
Sorry for my breaking change.
I also used old one, in my situation it was not broken. 
So I expected it did not effect, but it was different.
